#ifndef MTL_HEADER_REGEX_H
#define MTL_HEADER_REGEX_H

#define COORS_REGEX "CORNER_([A-Z]{2})_(LAT|LON)_PRODUCT"
#define RAD_MULT_REGEX "RADIANCE_MULT_BAND_([0-9]+)"
#define RAD_ADD_REGEX "RADIANCE_ADD_BAND_([0-9]+)"
#define AQUAIRED_DATE_REGEX "DATE_ACQUIRED"
#define FILE_DATE_REGEX "FILE_DATE"
#define SUN_ELEVATION_REGEX "SUN_ELEVATION"
#define SPACECRAFT_TYPE_REGEX "SPACECRAFT_ID"
#define QUALITY_REGEX "IMAGE_QUALITY([A-Z_]*)"
#define NAME_REGEX "LANDSAT_SCENE_ID"
#define CLOUD_COVER_REGEX "CLOUD_COVER"
#define CORRECTION_TYPE_REGEX "DATA_TYPE"
#define QUOT_VALUE_REGEX "\".*\""
#define IS_L8_REGEX "LANDSAT_8"
#define SCENE_NAME "\"[A-Z]{2}[0-9]{14}[A-Z]{3}[0-9]{2}\""
#define PATH_REGEX "(\/[a-zA-Z0-9_]*)+"

#endif // MTL_HEADER_REGEX_H
